from torch import Tensor
import torch
from torch import nn
import contextlib
from einops import rearrange

import math
from src.stgcn_layers import get_stgcn_chain
from transformers import MT5ForConditionalGeneration, T5Tokenizer
import warnings


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


from dataclasses import dataclass, field


@dataclass
class UniSignConfig:
    modes: list = field(default_factory=lambda: ["body", "left", "right", "face"])
    hidden_dim: int = 256
    mt5_path: str = "google/mt5-small"
    label_smoothing: float = 0.1
    tgt_lang: str = "English"
    proj_dim: int = 64


class UniSign(nn.Module):
    def __init__(self, config):
        super(UniSign, self).__init__()
        self.config = config

        self.modes = self.config.modes  # 'face'

        from src.stgcn_layers import GraphMP as Graph

        self.graph, A = {}, []
        # project (x,y,score) to hidden dim
        hidden_dim = config.hidden_dim
        self.proj_linear = nn.ModuleDict()
        for mode in self.modes:
            self.graph[mode] = Graph(layout=f"{mode}", strategy="distance", max_hop=1)
            A.append(
                torch.tensor(
                    self.graph[mode].A, dtype=torch.float32, requires_grad=False
                )
            )
            self.proj_linear[mode] = nn.Linear(3, config.proj_dim)

        self.gcn_modules = nn.ModuleDict()
        self.fusion_gcn_modules = nn.ModuleDict()
        spatial_kernel_size = A[0].size(0)
        for index, mode in enumerate(self.modes):
            self.gcn_modules[mode], final_dim = get_stgcn_chain(
                config.proj_dim,
                "spatial",
                (1, spatial_kernel_size),
                A[index].clone(),
                True,
            )
            self.fusion_gcn_modules[mode], _ = get_stgcn_chain(
                final_dim, "temporal", (5, spatial_kernel_size), A[index].clone(), True
            )

        self.gcn_final_dim = final_dim

        self.gcn_modules["left"] = self.gcn_modules["right"]
        self.fusion_gcn_modules["left"] = self.fusion_gcn_modules["right"]
        self.proj_linear["left"] = self.proj_linear["right"]

        mt5_model     = MT5ForConditionalGeneration.from_pretrained(config.mt5_path)
        mt5_tokenizer = T5Tokenizer.from_pretrained(config.mt5_path, legacy=False)
        mt5_embed_dim = mt5_model.config.d_model

        self.part_para = nn.Parameter(torch.zeros(hidden_dim * len(self.modes)))
        self.pose_proj = nn.Linear(self.gcn_final_dim * len(self.modes), mt5_embed_dim)

        self.apply(self._init_weights)

        self.tgt_lang = self.config.tgt_lang

        self.mt5_model = mt5_model
        self.mt5_tokenizer = mt5_tokenizer

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=0.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def maybe_autocast(self, dtype=torch.float32):
        # if on cpu, don't use autocast
        # if on gpu, use autocast with dtype if provided, otherwise use torch.float16
        # enable_autocast = self.device != torch.device("cpu")
        enable_autocast = True

        if enable_autocast:
            return torch.cuda.amp.autocast(dtype=dtype)
        else:
            return contextlib.nullcontext()

    def forward(self, src_input, tgt_input):
        # Pose branch forward
        features = []

        body_feat = None
        for part in self.modes:
            # project position to hidden dim
            proj_feat = self.proj_linear[part](src_input[part]).permute(
                0, 3, 1, 2
            )  # B,C,T,V
            # spatial gcn forward
            gcn_feat = self.gcn_modules[part](proj_feat)
            if part == "body":
                body_feat = gcn_feat

            else:
                assert not body_feat is None
                if part == "left":
                    gcn_feat = gcn_feat + body_feat[..., -2][..., None].detach()
                elif part == "right":
                    gcn_feat = gcn_feat + body_feat[..., -1][..., None].detach()
                elif part == "face":
                    gcn_feat = gcn_feat + body_feat[..., 0][..., None].detach()

                else:
                    raise NotImplementedError

            # temporal gcn forward
            gcn_feat = self.fusion_gcn_modules[part](gcn_feat)  # B,C,T,V
            pool_feat = gcn_feat.mean(-1).transpose(1, 2)  # B,T,C
            features.append(pool_feat)

        # concat sub-pose feature across token dimension
        inputs_embeds = torch.cat(features, dim=-1) + self.part_para
        inputs_embeds = self.pose_proj(inputs_embeds)

        prefix_token = self.mt5_tokenizer(
            [
                "Translate sign language video into {lang} spoken language text: ".format(
                    lang=self.tgt_lang
                )
            ]
            * inputs_embeds.size(0),
            padding="longest",
            truncation=True,
            return_tensors="pt",
        ).to(inputs_embeds.device)

        prefix_embeds = self.mt5_model.encoder.embed_tokens(prefix_token["input_ids"])
        inputs_embeds = torch.cat([prefix_embeds, inputs_embeds], dim=1)
        attention_mask = torch.cat(
            [prefix_token["attention_mask"], src_input["attention_mask"]], dim=1
        )

        tgt_input_tokenizer = self.mt5_tokenizer(
            tgt_input["labels"],
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=50,
        )

        labels = tgt_input_tokenizer["input_ids"]
        labels[labels == self.mt5_tokenizer.pad_token_id] = -100

        out = self.mt5_model(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            labels=labels.to(inputs_embeds.device),
            return_dict=True,
        )

        label = labels.reshape(-1)
        out_logits = out["logits"]
        logits = out_logits.reshape(-1, out_logits.shape[-1])
        loss_fct = torch.nn.CrossEntropyLoss(
            label_smoothing=self.config.label_smoothing, ignore_index=-100
        )
        loss = loss_fct(logits, label.to(out_logits.device, non_blocking=True))

        stack_out = {
            # use for inference
            "inputs_embeds": inputs_embeds,
            "attention_mask": attention_mask,
            "loss": loss,
        }

        return stack_out

    @torch.no_grad()
    def generate(self, pre_compute_item, max_new_tokens, num_beams):
        inputs_embeds = pre_compute_item["inputs_embeds"]
        attention_mask = pre_compute_item["attention_mask"]

        out = self.mt5_model.generate(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            num_beams=num_beams,
        )
        return out


@dataclass
class UniVQSignConfig:
    modes: list = field(default_factory=lambda: ["body", "left", "right", "face"])
    hidden_dim: int = 256
    mt5_path: str = "google/mt5-small"
    label_smoothing: float = 0.1
    tgt_lang: str = "English"
    proj_dim: int = 64
    part2code: dict = field(default_factory=lambda: {
        "body": 512,
        "left": 256,
        "right": 256,
        "face": 512,
    })


class UniVQSign(nn.Module):
    def __init__(self, config):
        super(UniVQSign, self).__init__()
        self.config = config

        self.modes = self.config.modes  # 'face'

        self.vq_modules = nn.ModuleDict()
        for mode in self.modes:
            # create embedding layer for each part
            self.vq_modules[mode] = nn.Embedding(
                config.part2code[mode], config.proj_dim
            )

        mt5_model     = MT5ForConditionalGeneration.from_pretrained(config.mt5_path)
        mt5_tokenizer = T5Tokenizer.from_pretrained(config.mt5_path, legacy=False)
        mt5_embed_dim = mt5_model.config.d_model

        self.part_para = nn.Parameter(torch.zeros(config.proj_dim * len(self.modes)))
        self.pose_proj = nn.Linear(config.proj_dim * len(self.modes), mt5_embed_dim)

        self.apply(self._init_weights)

        self.tgt_lang = self.config.tgt_lang

        self.mt5_model = mt5_model
        self.mt5_tokenizer = mt5_tokenizer

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=0.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def maybe_autocast(self, dtype=torch.float32):
        # if on cpu, don't use autocast
        # if on gpu, use autocast with dtype if provided, otherwise use torch.float16
        # enable_autocast = self.device != torch.device("cpu")
        enable_autocast = True

        if enable_autocast:
            return torch.cuda.amp.autocast(dtype=dtype)
        else:
            return contextlib.nullcontext()

    def forward(self, src_input, tgt_input):
        # Pose branch forward
        features = []

        body_feat = None
        for part in self.modes:
            vq_feat = self.vq_modules[part](src_input[part])  # B,T,C
            features.append(vq_feat)
            
        # concat sub-pose feature across token dimension
        inputs_embeds = torch.cat(features, dim=-1) + self.part_para
        inputs_embeds = self.pose_proj(inputs_embeds)

        prefix_token = self.mt5_tokenizer(
            [
                "Translate sign language video into {lang} spoken language text: ".format(
                    lang=self.tgt_lang
                )
            ]
            * inputs_embeds.size(0),
            padding="longest",
            truncation=True,
            return_tensors="pt",
        ).to(inputs_embeds.device)

        prefix_embeds = self.mt5_model.encoder.embed_tokens(prefix_token["input_ids"])
        inputs_embeds = torch.cat([prefix_embeds, inputs_embeds], dim=1)
        attention_mask = torch.cat(
            [prefix_token["attention_mask"], src_input["attention_mask"]], dim=1
        )

        tgt_input_tokenizer = self.mt5_tokenizer(
            tgt_input["labels"],
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=50,
        )

        labels = tgt_input_tokenizer["input_ids"]
        labels[labels == self.mt5_tokenizer.pad_token_id] = -100

        out = self.mt5_model(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            labels=labels.to(inputs_embeds.device),
            return_dict=True,
        )

        label = labels.reshape(-1)
        out_logits = out["logits"]
        logits = out_logits.reshape(-1, out_logits.shape[-1])
        loss_fct = torch.nn.CrossEntropyLoss(
            label_smoothing=self.config.label_smoothing, ignore_index=-100
        )
        loss = loss_fct(logits, label.to(out_logits.device, non_blocking=True))

        stack_out = {
            # use for inference
            "inputs_embeds": inputs_embeds,
            "attention_mask": attention_mask,
            "loss": loss,
        }

        return stack_out

    @torch.no_grad()
    def generate(self, pre_compute_item, max_new_tokens, num_beams):
        inputs_embeds = pre_compute_item["inputs_embeds"]
        attention_mask = pre_compute_item["attention_mask"]

        out = self.mt5_model.generate(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            num_beams=num_beams,
        )
        return out

def get_requires_grad_dict(model):
    param_requires_grad = {name: True for name, param in model.named_parameters()}
    param_requires_grad_right = {}
    for key in param_requires_grad.keys():
        if "left" in key:
            param_requires_grad_right[key.replace("left", "right")] = (
                param_requires_grad[key]
            )
    param_requires_grad = {**param_requires_grad, **param_requires_grad_right}
    params_to_update = {
        k: v for k, v in model.state_dict().items() if param_requires_grad.get(k, True)
    }

    return params_to_update
